import Head from 'next/head'
import HomePage from 'components/HomePage'
import ButtonLink from 'components/ButtonLink'
import routes from 'routes'

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
      <ButtonLink name="Project" link={routes.project.value}/>
      <ButtonLink name="Task" link={routes.todo.value}/>
      <ButtonLink name="Sign up" link={routes.signup.value}/>
      <ButtonLink name="Log in" link={routes.login.value}/>
    </div>
  )
}

export default Home
